[features]
seeds = false
skip-lint = false

[programs.localnet]
open_house = "B6g6uSjcFRn9U1p1wv4s7eggzUoFCn7koc2cnonrEZGJ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false
