[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
open_house = "B9jEbbSFoDZpmwqnRghE6zvUGQEZ3Bq2FVALL4FQYZPM"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://api.devnet.solana.com"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false
